### ISSUE TITLE
Add random watchlist-movie button

### ISSUE THREAD

**Issue by WinterIsCoding23** [WinterIsCoding23/movie-app#7]
**Value proposition**
As a user I want to click a random-button in order to have a random movie from my watchlist suggested to me.

**Description**

![Image](https://github.com/WinterIsCoding23/movie-app/assets/126890554/cf5fbdee-a161-4db9-a635-a481440018bf)

**Acceptance criteria**
- [ ] By clicking the random-watchlist-movie-button the user is directed to the detail page of a random movie from the Watchlist. 
- [x] The displayed movie is marked as a favourite.
- [ ] By clicking the random-watchlist-movie-button AGAIN the detail page of a DIFFERENT movie from the Watchlist is shown. 

**Tasks**
- [ ] Create a random-watchlist-movie-button in the Watchlist-component on the startpage (OR in the navbar, tbd)
- [ ] Link the onClick-event of the button to a random-function that shows a random watchlist-movie detail page 
- [ ] Replace the random movie-infos (title, image) on the startpage by a another random-movie-button and adapt the styling (size!) depending on the styling of the random-watchlist-movie-button
- [ ] Link the onClick-event of the random-movie-button to a random movie from the database (API)

**Comment by WinterIsCoding23** [comment]
- [ ] Add update of streaming-options in PUT-request (for case that watchlist-movie suddenly is available for streaming and other way round)
